<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <RootNamespace>Tily.Mcp</RootNamespace>
    <AssemblyName>tily-mcp</AssemblyName>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="ModelContextProtocol.Core" Version="2.2.0" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\Tily.Core\Tily.Core.csproj" />
  </ItemGroup>
</Project>
